name: Build and Deploy

on:
  push:
    branches: [main, master]
    tags: ['v*']
  workflow_dispatch:

jobs:
  build:
    uses: homelab/workflows/.gitea/workflows/docker-build.yml@main
    with:
      image_name: library/beads-viewer
      app_path: apps/beads-viewer
    secrets: inherit
